### ISSUE TITLE
서버가 클라이언트에 둘 이상의 응답을 보내려고 할 때 발생하는 오류 발생

### ISSUE THREAD

**Issue by hotdog16** [hotdog16/Pangsuni_Breado#1]
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:663:11)
    at ServerResponse.header (/home/hotdog/workspace/workspace_project/Pangsuni_Breado/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/hotdog/workspace/workspace_project/Pangsuni_Breado/node_modules/express/lib/response.js:170:12)
    at done (/home/hotdog/workspace/workspace_project/Pangsuni_Breado/node_modules/express/lib/response.js:1004:10)
    at /home/hotdog/workspace/workspace_project/Pangsuni_Breado/node_modules/nunjucks/src/environment.js:28:5
    at RawTask.call (/home/hotdog/workspace/workspace_project/Pangsuni_Breado/node_modules/asap/asap.js:40:19)
    at flush (/home/hotdog/workspace/workspace_project/Pangsuni_Breado/node_modules/asap/raw.js:50:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v18.15.0

**Comment by hotdog16** [comment]
문제 발생 후 검색을 통해 여러 가지를 시도해 봤습니다.
첫 번째로는 nunjucks.js가 문제인거 같다고 판단하여 node_module 삭제 후 재설치 했으나 해결되지 않았고,
두 번째로는 마지막 작업했던 파일들을 검토했으나 특별한 이상은 눈에 띄지 않았습니다.

**Comment by hotdog16** [comment]
controllers/page.js의 renderMain 부분에서 에러 발생.
  res.render("index", {
    title: "PangsuniBreado",
    user,
    // 메인 페이지 렌더링시 넌적스에 게시글 목록 전달
  });
next();
를
  res.render("index", {
    title: "PangsuniBreado",
    user,
    // 메인 페이지 렌더링시 넌적스에 게시글 목록 전달
  });
으로 수정
